[build]
  publish = "site"

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/site.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/themes/*"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "/vendor/*"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Cache-Control = "public, max-age=604800"
