#!/usr/bin/env bun
/**
 * Pull Doppler dev secrets → .env (values, never printed).
 * Refresh .env.example from secret names only (no values).
 *
 *   bun run env
 */
import { spawnSync } from "node:child_process";
import { chmodSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dir, "..");
const PROJECT = "calvinmaighan";
const CONFIG = "dev";
const SKIP_EXAMPLE = new Set(["DOPPLER_CONFIG", "DOPPLER_ENVIRONMENT", "DOPPLER_PROJECT"]);

function run(args, { inherit = false } = {}) {
	const result = spawnSync("doppler", args, {
		cwd: ROOT,
		encoding: "utf8",
		stdio: inherit ? "inherit" : ["ignore", "pipe", "pipe"],
	});
	if (result.status !== 0) {
		const err = (result.stderr || result.stdout || "").trim();
		console.error(err || `doppler ${args[0]} failed`);
		process.exit(result.status ?? 1);
	}
	return result.stdout ?? "";
}

// 1) Full secrets → .env (stdout redirected to file; not printed)
const envBody = run([
	"secrets",
	"download",
	"--no-file",
	"--format",
	"env",
	"--silent",
	"--project",
	PROJECT,
	"--config",
	CONFIG,
]);
const envPath = join(ROOT, ".env");
writeFileSync(envPath, envBody.endsWith("\n") ? envBody : `${envBody}\n`);
chmodSync(envPath, 0o600);

// 2) Names only → .env.example (API returns empty objects, never values)
const namesJson = run([
	"secrets",
	"--only-names",
	"--json",
	"--silent",
	"--project",
	PROJECT,
	"--config",
	CONFIG,
]);
const names = Object.keys(JSON.parse(namesJson))
	.filter((name) => !SKIP_EXAMPLE.has(name))
	.sort((a, b) => a.localeCompare(b));

const example = [
	"# Generated by `bun run env` from Doppler (names only — no secret values).",
	`# Project: ${PROJECT} · config: ${CONFIG}`,
	"#",
	...names.map((name) => `${name}=`),
	"",
].join("\n");

writeFileSync(join(ROOT, ".env.example"), example);

console.log(`Updated .env (${names.length + SKIP_EXAMPLE.size} keys) and .env.example (${names.length} placeholders)`);
